services:
  backend-herne:
    build: ./backend_herne
    ports:
      - "8091:8081"
    depends_on:
      - mosquitto

  backend:
    build: ./backend
    ports:
      - "8090:8080"
    depends_on:
      - database

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf



  database:
    image: postgres:latest
    restart: always
    volumes:
      - test:/usr
    environment:
      POSTGRES_DB: eventsManagement
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  smtp4dev:
    image: rnwood/smtp4dev:latest
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - "5000:80"
      # Change the number before : to the port the SMTP server should be accessible on
      - "2525:25"

    volumes:
      - smtp4dev-data:/smtp4dev
volumes:
  smtp4dev-data :
  test :
